language: node_js
node_js:
  - '8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cf' ]; then cd .. && eval "mv $currentfolder generator-cf" && cd generator-cf; fi
